### PR TITLE
changes to 0.6

### PR DESCRIPTION
**Pull request by MaximeBouton**
I updated the code to run in julia 0.6. It was only syntax changes, the tests pass with deprecation warning that should be fixed later:
- Inner constructor syntax (new() is not valid anymore for parametric type)
- POMDPToolbox.ParticleBelief is deprecated

Note: I tested with the updated version (see branch 0_6) of POMDPs and POMDPToolbox

### CODE REVIEW

**Comment by ebalaban** [comment]
@MaximeBouton looks like build checks are still failing (it's not just deprecation warnings). Would you mind taking a look?

**Comment by zsunberg** [comment]
Probably won't pass tests until we commit the 0.6 version of POMDPs.jl.

We'll probably do that tomorrow

**Comment by ebalaban** [comment]
Ok, let's wait with the merge then.

**Comment by zsunberg** [comment]
Sounds good. Will remind you when we get the tests to pass.

- Zach

**Comment by MaximeBouton** [comment]
The core packages POMDPs, POMDPToolbox and POMDPModels have been merged to METADATA, I restarted the build.

**Comment by ebalaban** [comment]
Looks great. Thank you for doing this @MaximeBouton .

**Pull request merged**
