### PR TITLE
Mersenne streams

### PR DESCRIPTION
**Pull request by zsunberg**
This is what it would look like to have MersenneTwister streams (in addition to the old DESPOTRandomNumber streams) as proposed in #9

### CODE REVIEW

**Comment by zsunberg** [comment]
Unfortunately, it appears that there was a slight performance regression when using the DESPOTRandomNumbers, i.e.
4x4 RockSample run tests:

Branch | master | any_updater (immutable DESPOTRandomNumbers) | mersenne_streams |
----|----|----|----|
Avg runtime | 14.63 | 13.38 |15.43 |

This appears to be because the type of random_streams is now Any. If I remove the Mersenne streams test and specify that random_streams is a RandomStreams in the mersenne_streams branch, I can recover the perfomance (the average is 13.46 sec). Thus, we can fix this later by parameterizing the solver with the stream type. But I don't want to add any more parameters to it right now.

**Comment by ebalaban** [comment]
My suggestion would be to put all this either in a separate branch or in a new package, as discussed in #10.

**Comment by zsunberg** [comment]
Hey @ebalaban , could you merge this into master? It contains two important steps towards getting the tests new tests in #10 to work (namely, (1) handling any belief updater and (2) introducing a more robust rng stream option). It does not break any of the RockSample tests.

Leaving it unmerged has impacted my workflow because it makes it more difficult for me to pull in changes that you have made to master.

**Comment by ebalaban** [comment]
Ok to delete this branch?

**Comment by zsunberg** [comment]
Yeah, OK to delete. thanks for merging!

**Pull request merged**
